#!/bin/python3

import binascii
import codecs
import sys

def englishWordsFrequency(xorStr):
    wordsSample = {
        'a': .08167, 'b': .01492, 'c': .02782, 'd': .04253,
        'e': .12702, 'f': .02228, 'g': .02015, 'h': .06094,
        'i': .06094, 'j': .00153, 'k': .00772, 'l': .04025,
        'm': .02406, 'n': .06749, 'o': .07507, 'p': .01929,
        'q': .00095, 'r': .05987, 's': .06327, 't': .09056,
        'u': .02758, 'v': .00978, 'w': .02360, 'x': .00150,
        'y': .01974, 'z': .00074, ' ': .13000
    }
    result = []

    for elem in xorStr.lower():
        score = wordsSample.get(chr(elem), 0)
        result.append(score)
    return sum(result)

def makeBruteForceXor(byteStr, key):
    xorStr = b''
    for elem in byteStr:
        xorStr += bytes([elem ^ key])
    return xorStr

def findKeyByteStr(ciphertext):
    cipherTmp = []

    for keyVal in range(256):
        xorMsg = makeBruteForceXor(ciphertext, keyVal)
        score = englishWordsFrequency(xorMsg)
        dataList = {
            'score' : score,
            'key' : keyVal,
            'line' : 0
            }
        cipherTmp.append(dataList)
    return sorted(cipherTmp, key = lambda x : x['score'], reverse = True)[0]

def singleByteXor(argv):
    try:
        with open(argv[1]) as f:
            txt = f.read()
            if (txt == ""):
                exit(84)
            txt = txt.splitlines()
    except:
        print("Error: file not found.")
        return (84)
    collectTmp = []
    line = 1
    i = 0
    for hexStr in txt:
        hexByte = bytes.fromhex(hexStr)
        collectTmp.append(findKeyByteStr(hexByte))
        collectTmp[i]['line'] += line
        line += 1
        i += 1
    finalScore = sorted(collectTmp, key = lambda x : x['score'], reverse = True)[0]
    print(finalScore['line'], end = ' ')
    print(hex(finalScore['key']).lstrip("0x").rstrip("L").upper())
    return (0)

if __name__ == '__main__':
    argv = sys.argv
    argc = len(argv)
    if (argc == 2):
        sys.exit(singleByteXor(argv))
    else:
        sys.exit(84)
